### ISSUE TITLE
How do I disable the INFO log messages?

### ISSUE THREAD

**Issue by ocyedwin** [jhalterman/lyra#50]
As above.

The log messages from lyra is too verbose. I tried adding "log4j.logger.net.jodah.lyra=OFF" to log4j-server.properties to no avail, any suggestions?

Thanks.

**Comment by jhalterman** [comment]
AFAIK what you're doing should work.

Lyra just uses the slf4j API. I'm assuming you have the `slf4j-log4j12` jar on your classpath which is why you're seeing log messages. If disabling an individual category, such as you're doing, doesn't work, you might try putting the `slf4j-nop` jar on your classpath which basically disables all slf4j logging.

**Comment by ocyedwin** [comment]
Sorry, just found the solution. 

adding "<logger name="net.jodah.lyra" level="OFF" />" to logback.xml config works.
